allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  core-js: false
  core-js-pure: false
  esbuild: set this to true or false

minimumReleaseAge: 0

publicHoistPattern:
  - '@mdx-js/react'
  - url-loader

registries:
  https://node-registry.bit.cloud:
    scopes:
      - '@pnpm'
      - '@bitdesign'
      - '@teambit'
    serverType: npm

packageExtensions:
  '@docusaurus/core':
    dependencies:
      prism-react-renderer: '*'
