allowBuilds:
  '@parcel/watcher': true
minimumReleaseAge: 0

patchedDependencies:
  '@pnpm/website.docs.docs-builder@0.2.0': patches/@pnpm__website.docs.docs-builder@0.2.0.patch
registries:
  https://node-registry.bit.cloud:
    scopes:
      - '@pnpm'
      - '@bitdesign'
      - '@teambit'
    serverType: npm
