name: Build Test

on: [pull_request]
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deploy
    env:
      COREPACK_ENABLE_AUTO_PIN: 0
    steps:
      - name: Checkout Commit
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0
      - name: Install pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        with:
          standalone: true
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
        env:
          LOCALE_CI: en
